version: "3.3"
services:
  prod:
    container_name: Weather
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN=${GH_TOKEN}

    volumes:
      - ./src:/app/src

    env_file:
      - .env
    networks:
      - small_bots
    environment:
      - PRODUCTION=true

    entrypoint: ["npm", "start"]
    restart: unless-stopped

networks:
  small_bots:
    name: small_bots_bridge