version: "3"
services:
  prod:
    network_mode: host
    build: .
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    env_file:
      - .env
    environment:
      - PRODUCTION=true
    restart: unless-stopped
    command: npm start
