version: "3.8"
services:
  prod:
    container_name: Weather
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

    env_file:
      - .env
    environment:
      - PRODUCTION=true

    entrypoint: ["npm", "start"]
    restart: unless-stopped
